### ISSUE TITLE
dqn_agent.pt 학습 정도 문의

### ISSUE THREAD

**Issue by blackaib** [Junyoungpark/Pytorch-AWAC#1]
ipynb에 DQN으로 데이터를 모으는 부분에서 dqn_agent.pt를 로딩해서 사용하고 있는데
dqn_agent.pt는 weight는 충분히 학습된 에이전트인가요? 아니면 40%정도 랜덤한 액션을 하도록 세팅된 상태에서 훈련된 agent인지요? 오프라인 데이터를 모으는 코드에 해당 DQN에 대해 40% 랜덤액션을 치도록 세팅한 부분은 없는것 같아 문의드립니다.

**Comment by Junyoungpark** [comment]
학습된 DQN agent는 해당문제를 풀 수 있는 agent 입니다. 대신 데이터를 모을 때 epsilon greedy 의  epsilon을 0.4 로 줘서 40% 확률로 random action 을 하도록 설정했습니다.

```python
    state_dict['epsilon'] = dqn.epsilon * .4 
    dqn.load_state_dict(state_dict)    
    offline_agent = dqn
    offline_budget = 50
```
